plugins:
  - jekyll-relative-links
relative_links:
  enabled: true
  collections: true
include:
  - README.md
  - LICENSE.md
url: https://writing-machine.github.io
baseurl: /oaio

title: Writing Machine
description: A machine is a thing. Things can not think. ...but some of them can thingk!

machine:
  name: Writing-Machine
  verb: Writing
  instructions_file: writing.txt
  token: openai.txt
  apiUrl: https://api.openai.com/v1/responses

app:
  worker_name: oaioapi.js

lm:
  model: o3-2025-04-16
  max_output_tokens: 100000
  reasoning_effort: high
  reasoning_summary: detailed
  temperature: 1.0

github_settings:
  owner: writing-machine
  repo: writing_machine
  file_name: machina.yaml
  branch: main
  token_file: github.txt
